language: go

go:
  - tip

install:
  - go get -u golang.org/x/lint/golint

script:
  - go build github.com/willeponken/elvisp/cmd/elvispd
  - go build github.com/willeponken/elvisp/cmd/elvispc
  - ./tool/test.bash github.com/willeponken/elvisp/cmd/...

after_success:
  - go get github.com/mattn/goveralls
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.txt -service=travis-ci -repotoken $COVERALLS_TOKEN
