language: go

go:
  - "1.13.x"

env:
  - GO111MODULE=on

install: true

script:
  - go build -mod=vendor github.com/willeponken/elvisp/cmd/elvispd
  - go build -mod=vendor github.com/willeponken/elvisp/cmd/elvispc
  - ./tool/test.bash github.com/willeponken/elvisp/cmd/...

after_success:
  - go get github.com/mattn/goveralls
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.txt -service=travis-ci -repotoken $COVERALLS_TOKEN
